---
- name: Automate Installation Tasks (System Update, Ansible, Flatpak, OS Utilities, ownCloud, ProtonVPN, TeamViewer)
  hosts: all
  become: yes
  vars:
    flatpak_apps:
      - com.brave.Browser
      - com.getpostman.Postman
      - com.github.micahflee.torbrowser-launcher
      - com.microsoft.Teams
      - com.sublimetext.three
      - com.visualstudio.code
      - com.ylsoftware.qmmp.Qmmp
      - io.github.mimbrero.WhatsAppDesktop
      - org.eclipse.Java
      - org.qbittorrent.qBittorrent
      - us.zoom.Zoom
      - org.freefilesync.FreeFileSync
      - org.videolan.VLC
      - com.github.PintaProject.Pinta
      - com.obsproject.Studio
      - com.mastermindzh.tidal-hifi

  tasks:
    # -------------------------
    # System Update
    # -------------------------
    - name: Update all system packages
      dnf:
        name: "*"
        state: latest
        update_cache: yes

    # -------------------------
    # Install Ansible
    # -------------------------
    - name: Install Ansible and dependencies
      dnf:
        name:
          - ansible-core
          - ansible
        state: present

    # -------------------------
    # Flatpak Apps Section
    # -------------------------
    - name: Add Flathub remote if not exists
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
      register: flatpak_remote
      changed_when: "'Added' in flatpak_remote.stdout"

    - name: Install Flatpak applications
      loop: "{{ flatpak_apps }}"
      command: flatpak install flathub {{ item }} -y
      register: flatpak_install
      failed_when: flatpak_install.rc != 0

    # -------------------------
    # OS Utilities Section
    # -------------------------
    - name: Install OS utilities
      dnf:
        name:
          - xclip
          - gnome-tweaks
          - htop
          - inxi
          - powertop
          - fastfetch
          - vim
          - gkrellm
          - snapd
          - tlp
          - cronie
          - libappindicator-gtk3
          - gnome-shell-extension-appindicator
          - google-chrome-stable
          - rsyslog
          - fdupes
          - podman-compose
          - setroubleshoot-server
          - strace
          - flameshot
          - libappindicator-gtk3 
          - gnome-shell-extension-appindicator
          - gnome-extensions-app
        state: present

    # -------------------------
    # ownCloud Section
    # -------------------------
    - name: Ensure dnf config-manager is installed
      dnf:
        name: dnf-command(config-manager)
        state: present

    - name: Download ownCloud GPG key
      get_url:
        url: https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Fedora_41/repodata/repomd.xml.key
        dest: /tmp/owncloud-key.gpg

    - name: Import ownCloud GPG key
      rpm_key:
        state: present
        key: /tmp/owncloud-key.gpg

    - name: Add ownCloud repository
      command: dnf config-manager addrepo --from-repofile=https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Fedora_41/owncloud-client.repo --overwrite
      register: owncloud_repo
      become: true

    - name: Clean dnf cache (ownCloud)
      command: dnf clean all

    - name: Install ownCloud client
      dnf:
        name: owncloud-client
        state: present
        update_cache: yes

    - name: Upgrade ownCloud client to latest version
      dnf:
        name: owncloud-client
        state: latest

    # -------------------------
    # TeamViewer Section
    # -------------------------
    - name: Import TeamViewer GPG key
      rpm_key:
        state: present
        key: "https://download.teamviewer.com/download/linux/signature/TeamViewer2017.asc"

    - name: Download TeamViewer RPM file
      get_url:
        url: "https://download.teamviewer.com/download/linux/teamviewer-host.x86_64.rpm"
        dest: /tmp/teamviewer-host.x86_64.rpm

    - name: Update OS packages (TeamViewer)
      command: dnf up -y

    - name: Install TeamViewer RPM package
      dnf:
        name: /tmp/teamviewer-host.x86_64.rpm
        state: present
        disable_gpg_check: yes  # Ensure GPG check is enabled after importing the key

    - name: Remove TeamViewer RPM file
      file:
        path: /tmp/teamviewer-host.x86_64.rpm
        state: absent

