---
- name: Setup daily update cron job
  hosts: localhost
  become: yes
  tasks:
    - name: "Create /etc/cron.daily/update file with shebang and update command"
      copy:
        dest: /etc/cron.daily/update
        content: |
          #!/bin/bash
          sudo dnf up -y
        owner: root
        group: root
        mode: '0755'

    - name: "Verify that /etc/cron.daily/update exists with correct permissions"
      stat:
        path: /etc/cron.daily/update
      register: cron_update_stat
